clusters=primary,secondary

primary.bootstrap.servers=kafka1:29092,kafka2:29092,kafka3:29092
secondary.bootstrap.servers=kafka2-1:29092,kafka2-2:29092,kafka2-3:29092

primary->secondary.enabled=true
primary->secondary.topics=shop\.products\.allowed|client\.search\.requests|client\.recommendation\.requests|analytics\.recommendations
primary->secondary.groups=product-filter|postgres-sink|client-api|spark|hdfs-ingestor

# Keep topic names identical on the analytics cluster instead of prefixing them with "primary.".
replication.policy.class=org.apache.kafka.connect.mirror.IdentityReplicationPolicy

primary->secondary.emit.checkpoints.enabled=true
primary->secondary.emit.checkpoints.interval.seconds=10
primary->secondary.emit.heartbeats.enabled=true
primary->secondary.emit.heartbeats.interval.seconds=5
sync.topic.acls.enabled=false
sync.topic.configs.enabled=true
refresh.topics.interval.seconds=10
refresh.groups.interval.seconds=10

checkpoints.topic.replication.factor=3
heartbeats.topic.replication.factor=3
offset-syncs.topic.replication.factor=3
config.storage.replication.factor=3
offset.storage.replication.factor=3
status.storage.replication.factor=3

primary.security.protocol=SSL
primary.ssl.truststore.location=/opt/bitnami/kafka/config/certs/kafka.truststore.jks
primary.ssl.truststore.password=changeit
primary.ssl.keystore.location=/opt/bitnami/kafka/config/certs/mirror-maker.keystore.jks
primary.ssl.keystore.password=changeit
primary.ssl.key.password=changeit

secondary.security.protocol=SSL
secondary.ssl.truststore.location=/opt/bitnami/kafka/config/certs/kafka.truststore.jks
secondary.ssl.truststore.password=changeit
secondary.ssl.keystore.location=/opt/bitnami/kafka/config/certs/mirror-maker.keystore.jks
secondary.ssl.keystore.password=changeit
secondary.ssl.key.password=changeit
