services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.13
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka-1:
    image: confluentinc/cp-kafka:7.4.13
    depends_on:
      - zookeeper
    volumes:
      - ./kafka/config/kafka-1.properties:/etc/kafka/kafka.properties
      - ./certs:/etc/kafka/secrets
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_FILE: /etc/kafka/kafka.properties
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    command: ["bash", "-c", "kafka-server-start /etc/kafka/kafka.properties"]
    ports:
      - "9092:9092"

  kafka-2:
    image: confluentinc/cp-kafka:7.4.13
    depends_on:
      - zookeeper
    volumes:
      - ./kafka/config/kafka-2.properties:/etc/kafka/kafka.properties
      - ./certs:/etc/kafka/secrets
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_FILE: /etc/kafka/kafka.properties
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    command: ["bash", "-c", "kafka-server-start /etc/kafka/kafka.properties"]
    ports:
      - "9093:9092"

  kafka-3:
    image: confluentinc/cp-kafka:7.4.13
    depends_on:
      - zookeeper
    volumes:
      - ./kafka/config/kafka-3.properties:/etc/kafka/kafka.properties
      - ./certs:/etc/kafka/secrets
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_FILE: /etc/kafka/kafka.properties
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    command: ["bash", "-c", "kafka-server-start /etc/kafka/kafka.properties"]
    ports:
      - "9094:9092"

  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    environment:
      KAFKA_CLUSTERS_0_NAME: Local Kafka Cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:9092,kafka-2:9092,kafka-3:9092
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SSL
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/clients/admin.truststore.jks
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_PASSWORD: changeit
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/clients/admin.keystore.jks
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_PASSWORD: changeit
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEY_PASSWORD: changeit
      KAFKA_TOPIC: my-topic
      DYNAMIC_CONFIG_ENABLED: true
    volumes:
      - ./certs:/etc/kafka/secrets
